package com.bottranslator.constant;

public class Payload
{
	public final static String GET_STARTED_PAYLOAD = "GET_STARTED_PAYLOAD";
	public final static String PERSISTENT_MENU_SHOW_CURRENT_SETTING = "PERSISTENT_MENU_SHOW_CURRENT_SETTING";
	public final static String PERSISTENT_MENU_CHANGE_INPUT_LANGUAGE = "PERSISTENT_MENU_CHANGE_INPUT_LANGUAGE";
	public final static String PERSISTENT_MENU_CHANGE_OUTPUT_LANGUAGE = "PERSISTENT_MENU_CHANGE_OUTPUT_LANGUAGE";

	public final static String QUICK_REPLY_INPUT_LANGUAGE = "QUICK_REPLY_INPUT_LANGUAGE";
	public final static String QUICK_REPLY_OUTPUT_LANGUAGE = "QUICK_REPLY_OUTPUT_LANGUAGE";
}
